version: '3'
services:
mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: criti-pixel
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - 3306:3306
volumes:
  postgres_db:
    driver: local