name: Continuous integration

on:
  push:
    branches: [ "CI-Test" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: mysql://root@127.0.0.1:3306/criti-pixel_test?charset=utf8mb4

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: criti-pixel_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      #- name: Install Dependencies
        #run: composer install --no-scripts --no-interaction --no-progress --prefer-dist

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h 127.0.0.1 -u root; do
            echo "Waiting for MySQL..."
            sleep 5
          done
          sleep 10

      - name: Create Database
        run: |
          composer install
          php bin/console doctrine:database:drop --force --if-exists --env=test
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:schema:update --force --env=test
          php bin/console doctrine:fixtures:load --env=test --no-interaction --purger=delete
          php bin/console sass:build

      - name: Tests
        run: php bin/phpunit

      - name: Analysis
        run: vendor/bin/phpstan analyse src tests --memory-limit=256M
