name: Continuous integration

on:
  push:
    branches: [ "CI-Test" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: mysql://root@127.0.0.1:3306/criti-pixel_test?charset=utf8mb4

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: criti-pixel_test
          MYSQL_ROOT_PASSWORD: ""
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - uses: actions/checkout@v4
        with:
          ref: CI-Test

      - name: Update Composer
        run: composer self-update

      - name: Install Dependencies
        run: composer install --no-scripts --no-interaction --no-progress --prefer-dist

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h 127.0.0.1 -u root; do
            echo "Waiting for MySQL..."
            sleep 5
          done
          sleep 10

      - name: Set up Database Schema and Load Fixtures
        run: |
          php bin/console doctrine:schema:update --force --env=test
          php bin/console doctrine:fixtures:load --env=test --no-interaction --purger=delete
          php bin/console sass:build

      - name: Install Symfony CLI
        run: wget https://get.symfony.com/cli/installer -O - | bash
      
      - name: Move Symfony CLI
        run: mv /home/runner/.symfony5/bin/symfony /usr/local/bin/symfony
          
      - name: Start Symfony Server
        run: symfony server:start --daemon --no-tls     

      - name: Check Symfony Server
        run: symfony server:status

      - name: Pause for server startup
        run: sleep 5
        
      - name: Tests
        env: 
          APP_ENV: test
        run: php bin/phpunit

      - name: Analysis
        run: vendor/bin/phpstan analyse src tests --memory-limit=256M
